### PR TITLE
WebSocket Subprotocol

### PR DESCRIPTION
**Pull request by ArtiomL**
Hi,

Some WebSocket servers **require** specifying the subprotocol value used in the `Sec-WebSocket-Protocol` header during the handshake.

I have added a new argument (`-s, --subprotocol`) that updates the connection protocol option.

Thank you in advance!

### CODE REVIEW

**Comment by jnordberg** [comment]
Thanks! Can you run `make lint` and commit? Should fix the tests

**Comment by ArtiomL** [comment]
Sorry, can't seem to figure out why this fails.
It works with `make lint` locally.

**Comment by ArtiomL** [comment]
OK got it.
I think everything is fixed now - could you please verify?
Thank you!

**Comment by jnordberg** [comment]
LGTM, have you verified that the option you added works as intended?

**Comment by ArtiomL** [comment]
Yes.
```
./ts-node ../../src/cli.ts ws://demos.kaazing.com/echo
NoSubProtocol
NoSubProtocol
^C
```

```
./ts-node ../../src/cli.ts ws://192.168.118.133:32773 -s echo
WithSubProtocol
WithSubProtocol
^C
```

**Comment by jnordberg** [comment]
Cheers!

**Comment by ArtiomL** [comment]
For some reason Travis fails with Node v7:
https://travis-ci.org/jnordberg/wscat/jobs/313232015

It runs OK with Node v7 locally.

`Error: listen EADDRINUSE :::41328` on their side?

**Comment by ArtiomL** [comment]
Works now.
This tool is amazing!

Are you planning to publish to npm as well?
https://www.npmjs.com/package/wscat2

Thank you.

**Pull request merged**
